"""initial schema baseline

This migration creates the full current schema in one step. It replaces two
earlier incremental migrations (20260613_01, 20260614_01) that were never able
to run from an empty database on their own, since they only ALTERed tables
that had always been created out-of-band via `Base.metadata.create_all()`.
This baseline is the single source of truth going forward; new schema changes
should be added as new migrations on top of this one.

Revision ID: 20260705_01
Revises:
Create Date: 2026-07-05

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260705_01"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("ADMIN", "LAWYER", "GENERAL_USER", name="user_role"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "legal_acts",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("normalized_title", sa.String(length=500), nullable=False),
        sa.Column("act_number", sa.String(length=50), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("certification_date", sa.Date(), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("source_name", sa.String(length=255), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("source_file_name", sa.String(length=500), nullable=False),
        sa.Column("stored_file_path", sa.String(length=1000), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column(
            "processing_status",
            sa.Enum(
                "UPLOADED",
                "PROCESSING",
                "PROCESSED",
                "FAILED",
                "VERIFIED",
                name="processing_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "parser_used",
            sa.Enum("DOCLING", "PYMUPDF", "OCR", "MANUAL", "UNKNOWN", name="parser_name"),
            nullable=False,
        ),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column("uploaded_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_legal_acts_act_number"), "legal_acts", ["act_number"], unique=False)
    op.create_index(op.f("ix_legal_acts_file_sha256"), "legal_acts", ["file_sha256"], unique=True)
    op.create_index(
        op.f("ix_legal_acts_normalized_title"), "legal_acts", ["normalized_title"], unique=False
    )
    op.create_index(
        op.f("ix_legal_acts_processing_status"), "legal_acts", ["processing_status"], unique=False
    )
    op.create_index(op.f("ix_legal_acts_title"), "legal_acts", ["title"], unique=False)
    op.create_index(op.f("ix_legal_acts_year"), "legal_acts", ["year"], unique=False)
    op.create_table(
        "act_sections",
        sa.Column("act_id", sa.String(length=36), nullable=False),
        sa.Column("section_number", sa.String(length=50), nullable=False),
        sa.Column("section_path", sa.String(length=100), nullable=True),
        sa.Column("heading", sa.String(length=500), nullable=True),
        sa.Column(
            "section_type",
            sa.Enum(
                "SECTION",
                "SUBSECTION",
                "PARAGRAPH",
                "SCHEDULE",
                "PART",
                "PREAMBLE",
                "OTHER",
                name="section_type",
            ),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("parent_section_id", sa.String(length=36), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum("PENDING", "VERIFIED", "REJECTED", "NEEDS_REVIEW", name="verification_status"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["act_id"],
            ["legal_acts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_section_id"],
            ["act_sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_act_sections_act_id"), "act_sections", ["act_id"], unique=False)
    op.create_index(
        op.f("ix_act_sections_section_number"), "act_sections", ["section_number"], unique=False
    )
    op.create_index(
        op.f("ix_act_sections_section_path"), "act_sections", ["section_path"], unique=False
    )
    op.create_index(
        op.f("ix_act_sections_sort_order"), "act_sections", ["sort_order"], unique=False
    )
    op.create_index(
        op.f("ix_act_sections_verification_status"),
        "act_sections",
        ["verification_status"],
        unique=False,
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("run_name", sa.String(length=255), nullable=False),
        sa.Column("act_id", sa.String(length=36), nullable=True),
        sa.Column("precision", sa.Float(), nullable=False),
        sa.Column("recall", sa.Float(), nullable=False),
        sa.Column("f1_score", sa.Float(), nullable=False),
        sa.Column("section_segmentation_accuracy", sa.Float(), nullable=True),
        sa.Column("total_gold_references", sa.Integer(), nullable=False),
        sa.Column("true_positives", sa.Integer(), nullable=False),
        sa.Column("false_positives", sa.Integer(), nullable=False),
        sa.Column("false_negatives", sa.Integer(), nullable=False),
        sa.Column("run_summary_json", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["act_id"],
            ["legal_acts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evaluation_runs_act_id"), "evaluation_runs", ["act_id"], unique=False)
    op.create_table(
        "processing_jobs",
        sa.Column("act_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "RUNNING", "COMPLETED", "FAILED", name="processing_job_status"),
            nullable=False,
        ),
        sa.Column("current_step", sa.String(length=255), nullable=False),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("summary_json", sa.JSON(), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["act_id"],
            ["legal_acts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_processing_jobs_act_id"), "processing_jobs", ["act_id"], unique=False)
    op.create_table(
        "evaluation_gold_references",
        sa.Column("act_id", sa.String(length=36), nullable=True),
        sa.Column("source_section_id", sa.String(length=36), nullable=True),
        sa.Column("expected_raw_text", sa.String(length=1000), nullable=False),
        sa.Column("expected_relationship_type", sa.String(length=50), nullable=False),
        sa.Column("expected_target_act_title", sa.String(length=500), nullable=True),
        sa.Column("expected_target_section_number", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["act_id"],
            ["legal_acts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_section_id"],
            ["act_sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evaluation_gold_references_act_id"),
        "evaluation_gold_references",
        ["act_id"],
        unique=False,
    )
    op.create_table(
        "legal_references",
        sa.Column("source_act_id", sa.String(length=36), nullable=False),
        sa.Column("source_section_id", sa.String(length=36), nullable=True),
        sa.Column("raw_reference_text", sa.String(length=1000), nullable=False),
        sa.Column("context_snippet", sa.Text(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum(
                "REFERS_TO",
                "AMENDS",
                "REPEALS",
                "INSERTS",
                "SUBSTITUTES",
                "ADDS",
                "COMMENCES",
                "DEFINES",
                "CROSS_REFERENCE",
                "UNKNOWN",
                name="relationship_type",
            ),
            nullable=False,
        ),
        sa.Column("target_act_title_raw", sa.String(length=500), nullable=True),
        sa.Column("target_act_number", sa.String(length=50), nullable=True),
        sa.Column("target_act_year", sa.Integer(), nullable=True),
        sa.Column("target_section_number", sa.String(length=50), nullable=True),
        sa.Column("target_section_path", sa.String(length=100), nullable=True),
        sa.Column("target_act_id", sa.String(length=36), nullable=True),
        sa.Column("target_section_id", sa.String(length=36), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column(
            "extraction_method",
            sa.Enum("REGEX", "NLP_RULE", "MANUAL", name="extraction_method"),
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum(
                "PENDING",
                "VERIFIED",
                "REJECTED",
                "NEEDS_REVIEW",
                name="reference_verification_status",
            ),
            nullable=False,
        ),
        sa.Column("verified_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_act_id"],
            ["legal_acts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_section_id"],
            ["act_sections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_act_id"],
            ["legal_acts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_section_id"],
            ["act_sections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_legal_references_relationship_type"),
        "legal_references",
        ["relationship_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_references_source_act_id"),
        "legal_references",
        ["source_act_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_references_source_section_id"),
        "legal_references",
        ["source_section_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_references_target_act_id"),
        "legal_references",
        ["target_act_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_references_target_section_id"),
        "legal_references",
        ["target_section_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_references_verification_status"),
        "legal_references",
        ["verification_status"],
        unique=False,
    )
    op.create_table(
        "saved_items",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "item_type",
            sa.Enum("ACT", "SECTION", "REFERENCE", name="saved_item_type"),
            nullable=False,
        ),
        sa.Column("act_id", sa.String(length=36), nullable=True),
        sa.Column("section_id", sa.String(length=36), nullable=True),
        sa.Column("reference_id", sa.String(length=36), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["act_id"],
            ["legal_acts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reference_id"],
            ["legal_references.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["act_sections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_saved_items_user_id"), "saved_items", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_saved_items_user_id"), table_name="saved_items")
    op.drop_table("saved_items")
    op.drop_index(op.f("ix_legal_references_verification_status"), table_name="legal_references")
    op.drop_index(op.f("ix_legal_references_target_section_id"), table_name="legal_references")
    op.drop_index(op.f("ix_legal_references_target_act_id"), table_name="legal_references")
    op.drop_index(op.f("ix_legal_references_source_section_id"), table_name="legal_references")
    op.drop_index(op.f("ix_legal_references_source_act_id"), table_name="legal_references")
    op.drop_index(op.f("ix_legal_references_relationship_type"), table_name="legal_references")
    op.drop_table("legal_references")
    op.drop_index(
        op.f("ix_evaluation_gold_references_act_id"), table_name="evaluation_gold_references"
    )
    op.drop_table("evaluation_gold_references")
    op.drop_index(op.f("ix_processing_jobs_act_id"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index(op.f("ix_evaluation_runs_act_id"), table_name="evaluation_runs")
    op.drop_table("evaluation_runs")
    op.drop_index(op.f("ix_act_sections_verification_status"), table_name="act_sections")
    op.drop_index(op.f("ix_act_sections_sort_order"), table_name="act_sections")
    op.drop_index(op.f("ix_act_sections_section_path"), table_name="act_sections")
    op.drop_index(op.f("ix_act_sections_section_number"), table_name="act_sections")
    op.drop_index(op.f("ix_act_sections_act_id"), table_name="act_sections")
    op.drop_table("act_sections")
    op.drop_index(op.f("ix_legal_acts_year"), table_name="legal_acts")
    op.drop_index(op.f("ix_legal_acts_title"), table_name="legal_acts")
    op.drop_index(op.f("ix_legal_acts_processing_status"), table_name="legal_acts")
    op.drop_index(op.f("ix_legal_acts_normalized_title"), table_name="legal_acts")
    op.drop_index(op.f("ix_legal_acts_file_sha256"), table_name="legal_acts")
    op.drop_index(op.f("ix_legal_acts_act_number"), table_name="legal_acts")
    op.drop_table("legal_acts")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
